[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Bakalaura_darbs"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
  "python-docx>=1.2.0",
  "lxml>=6.0.0",
  "pywin32>=311; platform_system == 'Windows'"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]